version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: | # use pip install to install dependencis
            sudo pip install -e . && pip install -r requirements-dev.txt
          name: Install dependencies
      - run:
          command: make check
          name: Run Tests

workflows:
  main:
    jobs:
      - build-and-test
